#version: '3.8'

services:
  # Metabase
  metabase-postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bi
    ports:
      - "5432:5432"
  metabase:
    image: metabase/metabase:v0.51.1.8
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - metabase-postgres