version: '3.8'

services:
  superset:
    image: apache/superset:3be6cef-py311
    container_name: superset
    command: >
      bash -c '
      pip install trino &&
      superset run -h 0.0.0.0 -p 8088 --with-threads --reload --debugger'
    ports:
      - "8088:8088"
    depends_on:
      - superset-db
      - superset-redis
    environment:
      SUPERSET_SECRET_KEY: "bE31aFE1UqbWsvPKEo7xwc/+Awy88iR8YjAGdYUrBsTTw4g+T8dxKoii"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py

  superset-init:
    image: apache/superset:3be6cef-py311
    container_name: superset_init
    depends_on:
      - superset-db
      - superset-redis
    entrypoint: /bin/bash
    command:
      - "-c"
      - |
        #!/bin/bash
        set -e
        ADMIN_USERNAME='admin'
        ADMIN_PASSWORD='admin'
        
        # Initialize the database
        echo "1 - Starting - Applying DB migrations"
        superset db upgrade
        echo "1 - Complete - Applying DB migrations"
        
        # Create an admin user
        echo "2 - Starting - Setting up admin user ($ADMIN_USERNAME / $ADMIN_PASSWORD)"
        superset fab create-admin \
            --username "$ADMIN_USERNAME" \
            --firstname Superset \
            --lastname Admin \
            --email "$ADMIN_USERNAME@example.com" \
            --password "$ADMIN_PASSWORD"
        echo "2 - Complete - Setting up admin user"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py

  superset-worker:
    image: apache/superset:3be6cef-py311
    container_name: superset_worker
    command: >
      bash -c '
      pip install trino &&
      celery --app=superset.tasks.celery_app:app worker'
    depends_on:
      - superset-redis
      - superset-db
    environment:
      SUPERSET_SECRET_KEY: "bE31aFE1UqbWsvPKEo7xwc/+Awy88iR8YjAGdYUrBsTTw4g+T8dxKoii"
    volumes:
      - ./superset_config.py:/app/pythonpath/superset_config.py

  superset-db:
    image: postgres:13
    container_name: superset_db
    environment:
      POSTGRES_DB: superset
      POSTGRES_USER: superset
      POSTGRES_PASSWORD: superset
    ports:
      - "5430:5432"

  superset-redis:
    image: redis:7
    container_name: superset_redis